### ISSUE TITLE
Icinga Business Process Modeling wont work anymore since Icinga DB Web v1.1.0

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingaweb2-module-businessprocess#413] opened 2023-10-02 11:20 UTC
## Describe the bug
Since the upgrade to the new version 1.1.0 of IcingaDB Web the Icinga Business Process Modeling v2.4.0 wont work anymore
The service shows:

## To Reproduce
Update to IcingaDB Web via apt update & apt upgrade.
(No other updates were available in my case, so it's really only the icingadb-web package.)

## Expected behavior
The business servive shows the correct state

## Screenshots
![image](https://github.com/Icinga/icingadb-web/assets/148245/f001c3af-98e2-4ae1-90a2-dee5bb41db3f)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.0
* Icinga Web 2 version (System - About): 2.12.0
* Web browser: Chrome
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Icinga DB version (`icingadb --version`): 1.1.1
* PHP version used (`php --version`): 7.4
* Server operating system and version: Debian 10

**Comment by sukhwinder33445** [comment] 2023-10-04 07:14
Duplicate of https://github.com/Icinga/icingaweb2-module-businessprocess/issues/411

**Closed by sukhwinder33445** 2023-10-04 07:14 UTC
