### ISSUE TITLE
Adding Nodes breaks UI

### ISSUE THREAD

**Issue by gla-bk** [Icinga/icingaweb2-module-businessprocess#335] opened 2022-07-21 12:02 UTC
## Describe the bug
The UI of a process in Business Process Module breaks after adding more Nodes.

## To Reproduce

1. Make 1 Primary Node (Firm A)
2. Make 1 Sub Node for a Location (Berlin)
3. Make 1 Sub Node for a Process Group (i.e. VMs)
4. Go back to Primary Node 

## Expected behavior
Can jump between Nodes and make as many nodes as possible without completly destroying the UI. 
I have not found a way to delete the Process. I can't access the Module anymore.

## Screenshots

![grafik](https://user-images.githubusercontent.com/72254340/180208263-eb19bbed-f40d-4684-a897-471c8ee86fbf.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10.1
* Web browser used: Firefox 
* Icinga 2 version used (`icinga2 --version`):  r2.13.3-1
* PHP version used (`php --version`): PHP 7.4.28
* Server operating system and version: Debian 11 (bullseye) 5.10.0-14-amd64

## Additional context
I have snapshots made in Hyper V, so I can go back and I can use the Module again, but after I add 3 nodes it breaks.

**Comment by nilmerg** [comment] 2022-07-22 07:38
Duplicate of #325

**Closed by nilmerg** 2022-07-22 07:38 UTC
