### ISSUE TITLE
Customized min-operator in a bp-file is not reflected in the gui

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2-module-businessprocess#439] opened 2024-02-22 09:45 UTC
## Describe the bug
A modified min-operator in a bp-file is not visualized in the gui.

## To Reproduce
Have a business process with lots of children and try to set the min at 16.

1. my bp has 32 children and I need a min of 16, but cant select it.  
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/34264690/3490a760-a160-4d2e-aff8-088ab77de5f9)

2. I have to modify the file:
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/34264690/203c9826-fad4-4681-bec4-400f6282b29a)
  
3. the config is valid, but ...
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/34264690/df3341dd-ff6d-4109-9802-bca9b840580e)

4. when I try to modify the process via gui at a later point, the selection falls back to the first item of the given dropdown menu, leading to possible mistakes and irritation.
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/34264690/bed37987-f64a-4ab2-9a3b-f7a341a4d6ff)

## Expected behavior
The gui should always be able to show the actual parametrisation of a business process. Also the integer values should be customizable. 

* Icinga Web 2 version and modules (System - About): 

businessprocess 2.4.0  
grafana 1.4.2  
monitoring 2.12.1  
networkdashboards 1.9.4  
pdfexport 0.10.2  

* Web browser used: edge
* Icinga 2 version used (`icinga2 --version`): 2.13.9
* PHP version used (`php --version`): 7.2.24
* Server operating system and version: Red Hat Enterprise Linux 8.8 (Ootpa) Kernel 4.18.0-477.15.1.el8_8.x86_64

**Comment by slalomsk8er** [comment] 2024-02-22 09:50
Your config isn't valid as there is not min16 operator. The config format is weird as in min1 to min9 are all separate operators and not an operator with an argument.

**Comment by nilmerg** [comment] 2024-02-22 09:56
Duplicate of #241

**Closed by nilmerg** 2024-02-22 09:56 UTC
